/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-surface": "#1a1b21",
        "on-tertiary-fixed-variant": "#773205",
        "on-background": "#1a1b21",
        "surface-variant": "#e3e1e9",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f1f0f7",
        "inverse-surface": "#2f3036",
        "secondary": "#555f6d",
        "error-container": "#ffdad6",
        "inverse-primary": "#b6c4ff",
        "outline": "#757682",
        "background": "#faf8ff",
        "tertiary-fixed-dim": "#ffb691",
        "primary-container": "#1e3a8a",
        "on-secondary-fixed-variant": "#3e4755",
        "surface-dim": "#dad9e1",
        "secondary-container": "#d6e0f1",
        "on-primary-fixed-variant": "#264191",
        "tertiary-fixed": "#ffdbcb",
        "on-secondary-container": "#596372",
        "surface-container-highest": "#e3e1e9",
        "outline-variant": "#c5c5d3",
        "primary-fixed": "#dce1ff",
        "surface-container": "#eeedf4",
        "error": "#ba1a1a",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#00164e",
        "on-tertiary-fixed": "#341100",
        "on-surface-variant": "#444651",
        "on-tertiary-container": "#f39461",
        "on-error": "#ffffff",
        "secondary-fixed": "#d9e3f4",
        "surface": "#faf8ff",
        "secondary-fixed-dim": "#bdc7d8",
        "on-secondary-fixed": "#121c28",
        "on-primary-container": "#90a8ff",
        "primary": "#00236f",
        "surface-container-high": "#e9e7ef",
        "tertiary": "#4b1c00",
        "primary-fixed-dim": "#b6c4ff",
        "surface-tint": "#4059aa",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f4f3fa",
        "tertiary-container": "#6e2c00",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-collapsed": "64px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "gutter": "24px",
        "stack-gap": "12px",
        "sidebar-width": "260px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "display": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "600"}],
        "display": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
